### PR TITLE
Fix nginx config

### PR DESCRIPTION
**Pull request by Rafi594**
Collabora online now works :)

### CODE REVIEW

**Comment by anmol26s** [comment]
How did you configured the collabora? 
1. What should be the value of the "Nextcloud domain" which is asked while installation? Is it with https or without https?
2. Why is the admin password asked while installation? Is there a admin interface for collabora?
3. What should be the value of the collabora app configuration in nextcloud app? It should be with https, port, url?

**Comment by Rafi594** [comment]
Nextcloud domain is the domain where Nextcloud is installed without https and /path
Admin password is for the admin interface at https://collabora.example.com/loleaflet/dist/admin/admin.html
In Nextcloud you need to set https://collabora.example.com/ without port.

**Comment by lapineige** [comment]
I can't use this branch, it fails when trying to start loolwsd service.

**Comment by lapineige** [comment]
As it works well, let's merge ?

**Pull request merged**
