### PR TITLE
Testing

### LINKED ISSUE #34: Failed installation in Ynh 4
Hello,
I've just migrated from Yunohost 3 to 4, and now I seems that I cannot install Collabora. Here is the log of one of the fail attempt : https://paste.yunohost.org/raw/pataguyoyu
Regards,
Taekiro.

### LINKED ISSUE #39: /etc/loolwsd/ca-chain.cert.pem not found
Hello helpful people :)

I have set up a fresh install of current **Yunohost 4.0.8.3 (stable)** on  **Debian10 (Kernel: 4.19.0-13-amd64)**. 
After successfully installing Nextcloud on cloud.mydomain.net I now tried to also install the **[Collabora App](https://github.com/YunoHost-Apps/collabora_ynh/):  (4.0.0~ynh2)** on collabora.mydomain.net but encountered the same error via WebGUI and CLI, but the first two errors/warnings that stuck out to me: 
`2021-01-06 09:30:40,414: WARNING - [Error] Jan 06 09:30:39 loolwsd[8401]: wsd-08401-08401 2021-01-06 08:30:39.032314 [ loolwsd ] TRC  Pre-read 17 file(s) from directory: /usr/share/loolwsd/loleaflet/dist: branding-tablet.css bundle.css framed.html global.js branding-mobile.css bundle.js admin-bundle.js loleaflet.html device-tablet.css device-desktop.css loleaflet-help.html framed.doc.html device-mobile.css branding.css signing-identities.html branding-desktop.css branding.js | wsd/FileServer.cpp:596`
and on when systemd is tryong too run loolwsd service:
`2021-01-06 09:30:40,420: WARNING - Jan 06 09:30:39 loolwsd[8401]: File not found: /etc/loolwsd/ca-chain.cert.pem`
Logs of install: https://paste.yunohost.org/raw/icexazoseq
journalctl -u loolwsd.service -b https://paste.yunohost.org/marivizifo.sql

I assume the former is not the main problem (?), but the latter is causing the trouble with starting up the loolwsd service. 
I assume I could try to substitute the ca-chain.cert.pem prior to installation - **but with what cert?** 
I have Let's encrypt certificates for all my three domains (yunohost/cloud/collabora).

Any help appreciated!

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

- Install is broken for stupid reasons
- Fix #39 
- Fix #34

## Solution

- Add config before installing the .deb to avoid collabora stupidly looking for a cert file that doesn't exist
- Fix the start of the service (it wasnt finding the proper pattern in the service log because ... the service was already started...)
- Fix nginx config such that it doesn't just display nginx default page when reaching the domain ...
- Use ynh_add_config for clarity (in fact requires a fix in the core ... on the way ...)

I don't know how to fully test the app though (gotta integrate it in nextcloud i suppose)

### CODE REVIEW

**Comment by alexAubin** [comment]
Trying to investigate with a user why the nextcloud integration wasnt working, encountered this kind of issue https://github.com/CollaboraOnline/Docker-CODE/issues/49 ... turns out we don't have the `<net>` block config in our current loolwsd.xml

In fact, looking at the diff with the default loolwsd.xml we have quite a few missing things (probably because of lack of maintenance on this app)

c.f. attached file savagely extracted from  https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-debian10/loolwsd_6.4.3-3_amd64.deb : 

[loolwsd.xml.orig.txt](https://github.com/YunoHost-Apps/collabora_ynh/files/5816211/loolwsd.xml.orig.txt)

Diff with : 

```
git diff --no-index loolwsd.xml.orig.txt loolwsd.xml
```

**Comment by Thatoo** [comment]
Does it work simply replacing the current yunohost loolwsd.xml file by the loolwsd.xml.orig.txt you extracted?

**Comment by alexAubin** [comment]
I don't know

**Review by ericgaspar — APPROVED** [review]

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Backup/restore tests seem to be successful in the old CI ...

**Comment by alexAubin** [comment]
Zblerg, not sure what happens from the log, there's nothing apart from a "Killed" in the systemd log, which could suggest that it's a resource issue, or that the process got killed by systemd after a "stop" being triggered ...

**Comment by alexAubin** [comment]
I savagely restarted the test just in case it's a tmp issue

**Comment by ericgaspar** [comment]
@alexAubin ping for merge?

**Comment by alexAubin** [comment]
We still need to address the previous comment https://github.com/YunoHost-Apps/collabora_ynh/pull/40#issuecomment-760370748 ... Like, I was discussing with a user the day I wrote it that could not integrate Collabora in Nextcloud because of the lack of some section of this config file .. But my todolist is too huge to have time to look deeper into this :/

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
